stages:
  make-field-files:
    foreach:
      ${submission}
    do:
      cmd: swgworkflow/make_field_files.py --output obs/${key}/fields.fits ${key}
      params:
        - submission.${key}.footprint
      deps:
        - ${item.footprint.footprint_file}
        - swgworkflow/make_field_files.py
      outs:
        - obs/${key}/fields.fits
  create-empty-xmls:
    foreach:
      ${submission}
    do:
      cmd: weaveworkflow/mos/workflow/mos_stage2/create_xml_files.py obs/${key}/fields.fits --outdir obs/${key}/01-empty
      deps:
        - obs/${key}/fields.fits
        - weaveworkflow/mos/workflow/mos_stage2/create_xml_files.py
      outs:
        - obs/${key}/01-empty
  add-targets:
    foreach:
      ${submission}
    do:
      cmd: weaveworkflow/mos/workflow/mos_stage3/add_targets_to_xmls.py  --catalogues ${item.catalogue_dir}/*.fits --outdir obs/${key}/02-targets obs/${key}/01-empty/*
      deps:
        - obs/${key}/01-empty
        - ${item.catalogue_dir}
        - weaveworkflow/mos/workflow/mos_stage3/add_targets_to_xmls.py
      outs:
        - obs/${key}/02-targets
  add-guide-and-calib-stars:
    foreach:
      ${submission}
    do:
      cmd: weaveworkflow/mos/workflow/mos_stage4/add_guide_and_calib_stars.py --outdir obs/${key}/03-guide-and-calib-stars obs/${key}/02-targets/*.xml
      deps:
        - obs/${key}/02-targets
        - weaveworkflow/mos/workflow/mos_stage4/add_guide_and_calib_stars.py
      outs:
        - obs/${key}/03-guide-and-calib-stars
  clean-xmls:
    foreach:
      ${submission}
    do:
      cmd: swgworkflow/clean_xml_targets.py --outdir obs/${key}/04-cleaned  obs/${key}/03-guide-and-calib-stars/*.xml
      deps:
        - obs/${key}/03-guide-and-calib-stars
        - swgworkflow/clean_xml_targets.py
      outs:
        - obs/${key}/04-cleaned
  configure:
    foreach:
      ${submission}
    do:
      cmd: swgworkflow/configurefields.py --epoch ${item.configure_epoch}  --sync --outdir obs/${key}/05-configured obs/${key}/04-cleaned/*.xml
      params:
        - submission.${key}.configure_epoch
      deps:
        - obs/${key}/04-cleaned
        - swgworkflow/configurefields.py
        - /soft/configure/configure
      outs:
        - obs/${key}/05-configured
  add-configured-to-catalogues:
    foreach:
      ${submission}
    do:
      cmd: swgworkflow/add_configured_to_catalogues.py --catalogues ${item.catalogue_dir}/*.fits --outdir ${item.catalogue_dir}-configured/  obs/${key}/05-configured/*.xml
      deps:
        - ${item.catalogue_dir}
        - swgworkflow/add_configured_to_catalogues.py
        - obs/${key}/05-configured
      outs:
        - ${item.catalogue_dir}-configured
  add-configured-to-external-source-lists:
    foreach:
      ${submission}
    do:
      cmd: swgworkflow/add_configured_to_source_lists.py --catalogues ${item.catalogue_dir}-configured/*.fits --outdir ${item.catalogue_dir}-external-configured/ ${item.external_cats}/*.fits
      deps:
        - ${item.catalogue_dir}-configured
        - ${item.external_cats}
        - swgworkflow/add_configured_to_source_lists.py
      outs:
        - ${item.catalogue_dir}-external-configured
  add-configured-to-internal-source-lists:
    foreach:
      ${submission}
    do:
      cmd: swgworkflow/add_configured_to_source_lists.py --catalogues ${item.catalogue_dir}-configured/*.fits --outdir ${item.catalogue_dir}-internal-configured/ ${item.internal_cats}/*.fits
      deps:
        - ${item.catalogue_dir}-configured
        - ${item.internal_cats}
        - swgworkflow/add_configured_to_catalogues.py
      outs:
        - ${item.catalogue_dir}-internal-configured


