stages:
  make-field-files:
    foreach: ${submission}
    do:
      cmd: swgworkflow/make_field_files.py --output output/${key}/fields.fits ${key}
      params:
      - submission.${key}.footprint
      deps:
      - ${item.footprint.footprint_file}
      - swgworkflow/make_field_files.py
      outs:
      - output/${key}/fields.fits
  create-empty-xmls:
    foreach: ${submission}
    do:
      cmd: weaveworkflow/mos/workflow/mos_stage2/create_xml_files.py output/${key}/fields.fits
        --outdir output/${key}/01-empty
      deps:
      - output/${key}/fields.fits
      - weaveworkflow/mos/workflow/mos_stage2/create_xml_files.py
      outs:
      - output/${key}/01-empty
  add-targets:
    foreach: ${submission}
    do:
      cmd: weaveworkflow/mos/workflow/mos_stage3/add_targets_to_xmls.py  --catalogues
        ${item.catalogue_dir}/*.fits --outdir output/${key}/02-targets output/${key}/01-empty/*
      deps:
      - output/${key}/01-empty
      - ${item.catalogue_dir}
      - weaveworkflow/mos/workflow/mos_stage3/add_targets_to_xmls.py
      outs:
      - output/${key}/02-targets
  add-guide-and-calib-stars:
    foreach: ${submission}
    do:
      cmd: >-
        weaveworkflow/mos/workflow/mos_stage4/add_guide_and_calib_stars.py
        --outdir output/${key}/03-guide-and-calib-stars output/${key}/02-targets/*.xml
      deps:
      - output/${key}/02-targets
      - weaveworkflow/mos/workflow/mos_stage4/add_guide_and_calib_stars.py
      outs:
      - output/${key}/03-guide-and-calib-stars
  clean-xmls:
    foreach: ${submission}
    do:
      cmd: swgworkflow/clean_xml_targets.py --outdir output/${key}/04-cleaned  output/${key}/03-guide-and-calib-stars/*.xml
      deps:
      - output/${key}/03-guide-and-calib-stars
      - swgworkflow/clean_xml_targets.py
      outs:
      - output/${key}/04-cleaned
  configure:
    foreach: ${submission}
    do:
      cmd: >-
        swgworkflow/configurefields.py --epoch ${item.configure_epoch} --sync
        --extra_configure_options ${item.configure_options}
        --multistage ${item.multistage}
        --outdir output/${key}/05-configured
        --xml_file_list output/${key}/04-cleaned/*.xml
      params:
      - submission.${key}.multistage
      - submission.${key}.configure_epoch
      - submission.${key}.configure_options
      deps:
      - output/${key}/04-cleaned
      - swgworkflow/configurefields.py
      - /soft/configure/configure
      outs:
      - output/${key}/05-configured
  add-configured-to-catalogues:
    foreach: ${submission}
    do:
      cmd: >-
        swgworkflow/add_configured_to_catalogues.py
        --catalogues ${item.catalogue_dir}/*.fits
        --outdir output/${key}/catalogs-configured/
        output/${key}/05-configured/*.xml
      deps:
      - ${item.catalogue_dir}
      - swgworkflow/add_configured_to_catalogues.py
      - output/${key}/05-configured
      outs:
      - output/${key}/catalogs-configured
  add-configured-to-external-source-lists:
    foreach: ${submission}
    do:
      cmd: >-
        swgworkflow/add_configured_to_source_lists.py
        --catalogues output/${key}/catalogs-configured/*.fits
        --suffix=-configured-${key}
        --outdir output/${key}/external-configured/ ${item.external_cats}/*.fits
      deps:
      - output/${key}/catalogs-configured
      - ${item.external_cats}
      - swgworkflow/add_configured_to_source_lists.py
      outs:
      - output/${key}/external-configured
  add-configured-to-internal-source-lists:
    foreach: ${submission}
    do:
      cmd: >-
        swgworkflow/add_configured_to_source_lists.py
        --catalogues output/${key}/catalogs-configured/*.fits
        --suffix=-configured-${key}
        --outdir output/${key}/internal-configured/ ${item.internal_cats}/*.fits
      deps:
      - output/${key}/catalogs-configured
      - ${item.internal_cats}
      - swgworkflow/add_configured_to_catalogues.py
      outs:
      - output/${key}/internal-configured

  downsample_SV_exp2_DR3_dwarfonly:
    cmd: >-
      mkdir -p catalogues/SV_exp2_DR3_dwarfonly_downsample &&
      swgworkflow/downsample_SVexp2.py
      --input_catalogue catalogues/SV_exp2_DR3_dwarfonly/cat_exp2_SV.fits
      --output_catalogue catalogues/SV_exp2_DR3_dwarfonly_downsample/cat_exp2_SV.fits
      --downsample_low_prio 0.5 --overwrite
    deps:
    - catalogues/SV_exp2_DR3_dwarfonly/cat_exp2_SV.fits
    - swgworkflow/downsample_SVexp2.py
    outs:
    - catalogues/SV_exp2_DR3_dwarfonly_downsample/cat_exp2_SV.fits

  downsample_SV_exp2_DR3_onlyprio8:
    cmd: >-
      mkdir -p catalogues/SV_exp2_DR3_dwarfonly_onlyprio8 &&
      swgworkflow/downsample_SVexp2.py
      --input_catalogue catalogues/SV_exp2_DR3_dwarfonly/cat_exp2_SV.fits
      --output_catalogue catalogues/SV_exp2_DR3_dwarfonly_onlyprio8/cat_exp2_SV.fits
      --downsample_low_prio 0.5 --only_prio 8 --overwrite
    deps:
    - catalogues/SV_exp2_DR3_dwarfonly/cat_exp2_SV.fits
    - swgworkflow/downsample_SVexp2.py
    outs:
    - catalogues/SV_exp2_DR3_dwarfonly_onlyprio8/cat_exp2_SV.fits

  downsample_SV_exp2_0p5:
    cmd: >-
      mkdir -p catalogues/SV_exp2_downsample0.5 &&
      swgworkflow/downsample_SVexp2.py
      --input_catalogue catalogues/SV_exp2/cat_exp2_SV.fits
      --output_catalogue catalogues/SV_exp2_downsample0.5/cat_exp2_SV.fits
      --downsample_low_prio 0.5 --overwrite
    deps:
    - catalogues/SV_exp2/cat_exp2_SV.fits
    - swgworkflow/downsample_SVexp2.py
    outs:
    - catalogues/SV_exp2_downsample0.5/cat_exp2_SV.fits
