field_template: 'weaveworkflow/mos/workflow/mos_stage1/aux/mos_field_template.fits'

submission:
  SV_exp1:
    footprint:
      footprint_file: 'data_repo/footprints/exp1_SV.fits'
      surveys:
        targsrvys: ['WS2021A1-028']
        max_fibres: [1000]
      progtemp: '11331.1+'
      obstemp: 'DACEB'
      keywords:
        trimester: '2020A1'
        author: 'chriswegg@gmail.com'
        report_verbosity: 1
        cc_report: 'vanessa.hill@oca.eu, gbattaglia@iac.es'
    configure_options: '""'
    multistage: "-1"
    catalogue_dir: 'catalogues/SV_exp1'
    configure_epoch: '2021.5'
    external_cats: 'data_repo/external_cats/exp1_SV_DR3'
    internal_cats: 'data_repo/internal_cats/exp1_SV_DR3'

  SV_exp2_targprio_tweak:
    footprint:
      footprint_file: 'data_repo/footprints/exp2_SV.fits'
      surveys:
        targsrvys: ['WS2021A1-029']
        max_fibres: [1000]
      progtemp: '11331.1+'
      obstemp: 'DACEB'
      keywords:
        trimester: '2020A1'
        author: 'chriswegg@gmail.com'
        report_verbosity: 1
        cc_report: 'vanessa.hill@oca.eu, gbattaglia@iac.es'
    configure_options: '""'
    multistage: "4"
    catalogue_dir: 'catalogues/SV_exp2_targprio_tweak'
    configure_epoch: '2021.5'
    external_cats: 'data_repo/external_cats/exp2_SV_DR3'
    internal_cats: 'data_repo/internal_cats/exp2_SV_DR3'

  SV_exp2:
    footprint:
      footprint_file: 'data_repo/footprints/exp2_SV.fits'
      surveys:
        targsrvys: ['WS2021A1-029']
        max_fibres: [1000]
      progtemp: '11331.1+'
      obstemp: 'DACEB'
      keywords:
        trimester: '2020A1'
        author: 'chriswegg@gmail.com'
        report_verbosity: 1
        cc_report: 'vanessa.hill@oca.eu, gbattaglia@iac.es'
    configure_options: '""'
    multistage: "8"
    catalogue_dir: 'catalogues/SV_exp2'
    configure_epoch: '2021.5'
    external_cats: 'data_repo/external_cats/exp2_SV_DR3'
    internal_cats: 'data_repo/internal_cats/exp2_SV_DR3'

  SV_exp2_DR3_dwarfsonly:
    footprint:
      footprint_file: 'data_repo/footprints/exp2_SV.fits'
      surveys:
        targsrvys: ['WS2021A1-029']
        max_fibres: [1000]
      progtemp: '11331.1+'
      obstemp: 'DACEB'
      keywords:
        trimester: '2020A1'
        author: 'chriswegg@gmail.com'
        report_verbosity: 1
        cc_report: 'vanessa.hill@oca.eu, gbattaglia@iac.es'
    configure_options: '""'
    multistage: "-1"
    catalogue_dir: 'catalogues/SV_exp2_DR3_dwarfonly'
    configure_epoch: '2021.5'
    external_cats: 'data_repo/external_cats/exp2_SV_DR3'
    internal_cats: 'data_repo/internal_cats/exp2_SV_DR3'

  SV_exp2_DR3_dwarfsonly_onlyprio8_multistage:
    footprint:
      footprint_file: 'data_repo/footprints/exp2_SV.fits'
      surveys:
        targsrvys: ['WS2021A1-029']
        max_fibres: [1000]
      progtemp: '11331.1+'
      obstemp: 'DACEB'
      keywords:
        trimester: '2020A1'
        author: 'chriswegg@gmail.com'
        report_verbosity: 1
        cc_report: 'vanessa.hill@oca.eu, gbattaglia@iac.es'
    configure_options: '""'
    multistage: "4"
    catalogue_dir: 'catalogues/SV_exp2_DR3_dwarfonly_onlyprio8'
    configure_epoch: '2021.5'
    external_cats: 'data_repo/external_cats/exp2_SV_DR3'
    internal_cats: 'data_repo/internal_cats/exp2_SV_DR3'

  SV_exp2_DR3_dwarfsonly_onlyprio8_default:
    footprint:
      footprint_file: 'data_repo/footprints/exp2_SV.fits'
      surveys:
        targsrvys: ['WS2021A1-029']
        max_fibres: [1000]
      progtemp: '11331.1+'
      obstemp: 'DACEB'
      keywords:
        trimester: '2020A1'
        author: 'chriswegg@gmail.com'
        report_verbosity: 1
        cc_report: 'vanessa.hill@oca.eu, gbattaglia@iac.es'
    configure_options: '""'
    multistage: "-1"
    catalogue_dir: 'catalogues/SV_exp2_DR3_dwarfonly_onlyprio8'
    configure_epoch: '2021.5'
    external_cats: 'data_repo/external_cats/exp2_SV_DR3'
    internal_cats: 'data_repo/internal_cats/exp2_SV_DR3'

  SV_exp2_downsample_0p5:
    footprint:
      footprint_file: 'data_repo/footprints/exp2_SV.fits'
      surveys:
        targsrvys: ['WS2021A1-029']
        max_fibres: [1000]
      progtemp: '11331.1+'
      obstemp: 'DACEB'
      keywords:
        trimester: '2020A1'
        author: 'chriswegg@gmail.com'
        report_verbosity: 1
        cc_report: 'vanessa.hill@oca.eu, gbattaglia@iac.es'
    configure_options: '""'
    multistage: "4"
    catalogue_dir: 'catalogues/SV_exp2_downsample0.5'
    configure_epoch: '2021.5'
    external_cats: 'data_repo/external_cats/exp2_SV'
    internal_cats: 'data_repo/internal_cats/exp2_SV'


  pointed:
    footprint:
      footprint_file: 'data_repo/footprints/pointed_20AT1.fits'
      surveys:
        targsrvys: ['GA-LRhighlat']
        max_fibres: [1000]
      progtemp: '11331.1+'
      obstemp: 'DACEB'
      keywords:
        trimester: '2020A1'
        author: 'chriswegg@gmail.com'
        report_verbosity: 1
        cc_report: 'vanessa.hill@oca.eu, gbattaglia@iac.es'
    configure_options: '""'
    multistage: "-1"
    catalogue_dir: 'catalogues/pointed'
    configure_epoch: '2021.5'
    external_cats: 'data_repo/external_cats/pointed_2021A1'
    internal_cats: 'data_repo/internal_cats/pointed_2021A1'


  shared:
    footprint:
      footprint_file: 'data_repo/footprints/shared_20AT1.fits'
      surveys:
        targsrvys: ['GA-LRhighlat', 'WQ', 'WL']
        max_fibres: [630, 130, 130]
      progtemp: '11331.1+'
      obstemp: 'DACEB'
      keywords:
        trimester: '2020A1'
        author: 'chriswegg@gmail.com'
        report_verbosity: 1
        cc_report: 'vanessa.hill@oca.eu, gbattaglia@iac.es, WL@weave, WQ@weave'
    configure_options: '""'
    multistage: "-1"
    catalogue_dir: 'catalogues/shared'
    configure_epoch: '2021.5'
    external_cats: 'data_repo/external_cats/shared_2021A1'
    internal_cats: 'data_repo/internal_cats/shared_2021A1'
